services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: meteo_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: meteo_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules